// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx1LyPwUpN_auqdntW7psgsZfrgaCYeFw',
    appId: '1:62183933558:web:7126cd03f6141d22f18157',
    messagingSenderId: '62183933558',
    projectId: 'labtest2-60191',
    authDomain: 'labtest2-60191.firebaseapp.com',
    storageBucket: 'labtest2-60191.appspot.com',
    measurementId: 'G-23HYC93MVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHu4CMPfYQkFk2ppx5l9yGeDym4oEwyrc',
    appId: '1:62183933558:android:b4a8278db45ad758f18157',
    messagingSenderId: '62183933558',
    projectId: 'labtest2-60191',
    storageBucket: 'labtest2-60191.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoqsYO4GooyE00mII8O65ltI-6Gp-FkiU',
    appId: '1:62183933558:ios:336d46a854d2def8f18157',
    messagingSenderId: '62183933558',
    projectId: 'labtest2-60191',
    storageBucket: 'labtest2-60191.appspot.com',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoqsYO4GooyE00mII8O65ltI-6Gp-FkiU',
    appId: '1:62183933558:ios:336d46a854d2def8f18157',
    messagingSenderId: '62183933558',
    projectId: 'labtest2-60191',
    storageBucket: 'labtest2-60191.appspot.com',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx1LyPwUpN_auqdntW7psgsZfrgaCYeFw',
    appId: '1:62183933558:web:8751f25fdc158403f18157',
    messagingSenderId: '62183933558',
    projectId: 'labtest2-60191',
    authDomain: 'labtest2-60191.firebaseapp.com',
    storageBucket: 'labtest2-60191.appspot.com',
    measurementId: 'G-CVCFM8HPE4',
  );
}
